<?php

/**
 * Implementation of hook_install().
 */
function ca_services_install() {
  variable_set('ca_services_list_template', 'ca_services_list_template_one');
  variable_set('ca_services_node_template', 'ca_services_node_template_one');
}

/**
 * Implementation of hook_uninstall().
 */
function ca_services_uninstall() {
  variable_del('ca_services_list_template');
  variable_del('ca_services_node_template');
}
