<?php

include_once('ca_services.features.inc');

/**
 * Implementation of hook_perm().
 */
function ca_services_perm() {
  return array('ca_services change templates'); 
}

/**
 * Implementation of hook_menu().
 */
function ca_services_menu() {
  $items['admin/settings/ca_services'] = array(
    'title' => 'CA Services: Admin',
    'description' => 'Change the look and feel of the ca_services module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_services_admin_settings_form'),
    'access arguments' => array('ca_services change templates'),
    'file' => 'ca_services.admin.inc',
    'file path' => drupal_get_path('module', 'ca_services') . '/includes',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function ca_services_action_info() {
  return array(
    'ca_services_add_ca_services_admin_action' => array(
      'type' => 'user',
      'description' => t('Add services administrator role'),
    ),
    'ca_services_remove_ca_services_admin_action' => array(
      'type' => 'user',
      'description' => t('Remove services administrator role'),
    ),
    'ca_services_add_services_writer_action' => array(
      'type' => 'user',
      'description' => t('Add services writer role'),
    ),
    'ca_services_remove_services_writer_action' => array(
      'type' => 'user',
      'description' => t('Remove services writer role'),
    ),
  );
}

function ca_services_add_ca_services_admin_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'services administrator') {
      $add_roles[$key] = $role;
    }
  }
  $roles += $add_roles;
  user_save($user, array('roles' => $roles));
}

function ca_services_add_ca_services_admin_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Promote to Services Administrator',
  );
  return $form;
}

function ca_services_add_ca_services_admin_action_submit(&$form, &$form_state) {
  
}

function ca_services_remove_ca_services_admin_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'services administrator') {
      $remove_roles[$key] = $role;
    }
  }
  $roles = array_diff($roles, $remove_roles);
  user_save($user, array('roles' => $roles));
}

function ca_services_remove_ca_services_admin_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Demote from Services Administrator',
  );
  return $form;
}

function ca_services_remove_ca_services_admin_action_submit(&$form, &$form_state) {
  
}

function ca_services_add_services_writer_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'services writer') {
      $add_roles[$key] = $role;
    }
  }
  $roles += $add_roles;
  user_save($user, array('roles' => $roles));
}

function ca_services_add_services_writer_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Promote to Services Writer',
  );
  return $form;
}

function ca_services_add_services_writer_action_submit(&$form, &$form_state) {
  
}

function ca_services_remove_services_writer_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'services writer') {
      $remove_roles[$key] = $role;
    }
  }
  $roles = array_diff($roles, $remove_roles);
  user_save($user, array('roles' => $roles));
}

function ca_services_remove_services_writer_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Demote from Services Writer',
  );
  return $form;
}

function ca_services_remove_services_writer_action_submit(&$form, &$form_state) {
  
}  

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function ca_services_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;;
  }
}

/**
 * Implementation of hook_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask).
 */
function ca_services_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask){
  if ($subtask['name'] == 'ca_services' || $subtask['name'] == 'home' || $task['name'] == 'node_view') {
    drupal_add_css(drupal_get_path('module', 'ca_services') . "/css/ca_services.css", 'module', 'all', FALSE);
  }
}

/**
 * Implementation of hook_views_pre_render().
 */
function ca_services_views_pre_render(&$view) {
  if ($view->name == 'services') {
    drupal_add_css(drupal_get_path('module', 'ca_services') . "/css/ca_services.css", 'module', 'all', FALSE);
  }
}

